name: todoapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_local_notifications: ^13.0.0
  flutter_localization: null
  flutter_native_splash: ^2.2.19
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^1.1.6
  get: ^4.6.5
  google_mobile_ads: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  http: ^0.13.5
  intl: null
  isoweek: ^1.1.4
  share_plus: ^6.3.1
  timezone: ^0.9.1
  url_launcher: ^6.1.10
  introduction_screen: ^3.1.7

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#FFC700"
  image: "assets/splash_logo.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"
