name: todoapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  calendar_timeline: ^1.0.5
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  http: ^0.13.5
  isoweek: ^1.1.4
  path_provider: ^2.0.11
  sqflite: ^2.1.0+1

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
